export const ROUTES = {
  auth: {
    login: "/login",
  },
  dashboard: {
    home: "/",
    profile: "/profile",
    transactions: "/transactions",
    sources: "/sources",
    billing: "/billing",
    installments: "/installments",
    debt: "/debt",
    reports: "/reports",
    categories: "/categories",
    savings: "/savings",
    investments: "/investments",
    tags: "/tags",
    automation: "/automation",
    notifications: "/notifications",
    settings: "/settings",
    settingsProfile: "/settings/profile",
    settingsSecurity: "/settings/security",
    settingsNotifications: "/settings/notifications",
    settingsPreferences: "/settings/preferences",
    settingsChangeEmail: "/settings/change-email",
    settingsPrivacy: "/settings/privacy",
    settingsMembers: "/settings/members",
  },
} as const;
